spring.application.name=vms

spring.datasource.url=jdbc:postgresql://localhost:5432/vms
spring.datasource.username=postgres
spring.datasource.password=2489
spring.jpa.hibernate.ddl-auto=update
server.port=8081
